
/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: 12 Jul 2022
*/


/*
DROP TABLE IF EXISTS `duration`;
DROP TABLE IF EXISTS `Saturday`;
DROP TABLE IF EXISTS `schedule`;
DROP TABLE IF EXISTS `previous_jobs`;
DROP TABLE IF EXISTS `charges`;
DROP TABLE IF EXISTS `certificate`;
DROP TABLE IF EXISTS `Appointment`.`Staff`;

DROP SCHEMA IF EXISTS `Appointment`;
*/


CREATE SCHEMA IF NOT EXISTS `Appointment` DEFAULT CHARACTER SET utf8;


CREATE TABLE `Appointment`.`Staff` (
    `id` INT (10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR (100) NOT NULL,
    `work_location` VARCHAR (100) NOT NULL,
    `phone` VARCHAR (100) NOT NULL,
    `email` VARCHAR (100),
    `desc` TEXT,
    `previous_jobs` VARCHAR (100),
    `current_job` VARCHAR (100),
    `certificates` VARCHAR (100),
    `charges` VARCHAR (100),
    `sechdule` VARCHAR (100),
    PRIMARY KEY (`id`),
    UNIQUE INDEX staff_phone_unique (`phone`),
    UNIQUE INDEX staff_email_unique (`email`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8;


CREATE TABLE `certificate` (
    `id` INT (10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR (100) NOT NULL,
    `file` VARCHAR (100) NOT NULL,
    `staff_id` VARCHAR (100),
    PRIMARY KEY (`id`),
    UNIQUE INDEX certificate_name_unique (`name`),
    UNIQUE INDEX certificate_file_unique (`file`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8;


CREATE TABLE `charges` (
    `id` INT (10) NOT NULL AUTO_INCREMENT,
    `physical` INT (10) NOT NULL,
    `online` INT (10) NOT NULL,
    `staff_id` VARCHAR (100),
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8;


CREATE TABLE `previous_jobs` (
    `id` INT (10) NOT NULL AUTO_INCREMENT,
    `position` VARCHAR (100) NOT NULL,
    `duration` VARCHAR (100),
    `organization` VARCHAR (100),
    `staff_id` VARCHAR (100),
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8;


CREATE TABLE `schedule` (
    `id` INT (10) NOT NULL AUTO_INCREMENT,
    `saterday` VARCHAR (100),
    `sunday` VARCHAR (100),
    `monday` VARCHAR (100),
    `wenday` VARCHAR (100),
    `thursday` VARCHAR (100),
    `friday` VARCHAR (100),
    `staff_id` VARCHAR (100),
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8;


CREATE TABLE `Saturday` (
    `id` INT (10) NOT NULL AUTO_INCREMENT,
    `session1` TINYINT (1),
    `session2` TINYINT (1),
    `session3` TINYINT (1),
    `session4` TINYINT (1),
    `session5` TINYINT (1),
    `session6` TINYINT (1),
    `schedule_id` VARCHAR (100),
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8;


CREATE TABLE `duration` (
    `id` INT (10) NOT NULL AUTO_INCREMENT,
    `start` DATETIME,
    `end` DATETIME,
    `previous_job_id` VARCHAR (100),
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8;


ALTER TABLE `previous_jobs`
ADD FOREIGN KEY staff_previous_jobs_fk (`staff_id`) REFERENCES `Appointment`.`Staff`(`previous_jobs`);

ALTER TABLE `duration`
ADD FOREIGN KEY previous_jobs_duration_fk (`previous_job_id`) REFERENCES `previous_jobs`(`duration`);

ALTER TABLE `certificate`
ADD FOREIGN KEY staff_certificate_fk (`staff_id`) REFERENCES `Appointment`.`Staff`(`certificates`);

ALTER TABLE `charges`
ADD FOREIGN KEY staff_charges_fk (`staff_id`) REFERENCES `Appointment`.`Staff`(`charges`);

ALTER TABLE `schedule`
ADD FOREIGN KEY staff_schedule_fk (`staff_id`) REFERENCES `Appointment`.`Staff`(`sechdule`);

ALTER TABLE `Saturday`
ADD FOREIGN KEY schedule_saturday_fk (`schedule_id`) REFERENCES `schedule`(`saterday`);




